on:
  issue_comment:
  pull_request_review_comment:
  pull_request_review:
  pull_request:
    types:
    - opened
    - edited

jobs:
  pr_commented:
    # This job only runs for pull request comments
    name: PR comment
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "A comment on PR `cat ${{ github.event_path }}`"