on:
  issue_comment:
  pull_request_review_comment:
  pull_request_review:
  pull_request:
    types:
    - opened
    - edited

jobs:
  pr_commented:
    # This job only runs for pull request comments
    name: PR comment
    runs-on: ubuntu-latest
    steps:
      - uses: actions/github-script@v6
        with:
          script: |
            if (context.eventName === "issue_comment" && context.payload.issue.pull_request === undefined)
              console.log("Issue comment is ignored");
              return
            }
            const pr = await github.rest.pulls.get({
              owner: context.issue.owner,
              repo: context.issue.repo,
              pull_number: context.issue.number
            })
            var comments = []
            comments.push(pr.body)
            console.log(comments)