on: [issue_comment, pull_request_review_comment, pull_request_review]

jobs:
  pr_commented:
    # This job only runs for pull request comments
    name: PR comment
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "A comment on PR $NUMBER"
        env:
          NUMBER: ${{ github.event }}